version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: datagarden-crawler-img
    env_file: 
      - ./datagarden-crawler/.env
    container_name: datagarden-crawler-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80
    networks:
      - datagarden-crawler-network
  db:
    image: mysql:8.0
    container_name: datagarden-crawler-db
    env_file: 
      - ./datagarden-crawler/.env
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "${DB_DATABASE}"]
        timeout: 10s
        retries: 10
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - datagarden-crawler-network
networks:
  datagarden-crawler-network:
    driver: bridge
